services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/config
      - ./translation-worker:/usr/src/app/translation-worker
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE=${DATABASE}
      - RABBITMQ=${RABBITMQ}
      - PORT=${PORT}
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: translation-worker
    command: npm run start:worker:watch
    volumes:
      - ./api:/usr/src/app/api
      - ./translation-worker:/usr/src/app/translation-worker
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      - DATABASE=${DATABASE}
      - RABBITMQ=${RABBITMQ}
    restart: unless-stopped

volumes:
  mongo-data: